server:
  port: 8080
spring:
  application:
    name: example-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
